name: workflow-3

on: workflow_dispatch

jobs:
    ubuntu-echo:
          runs-on: ubuntu-latest
          steps:
            - name: show OS
              run: |
                  echo "this is a ubunutu machince"
                  echo "RunnerOS: $RUNNER_OS"
